### ISSUE TITLE
Generate MPU9250 Circuit Diagram in EAGLE

### ISSUE THREAD

**Issue by mchartigan** [purdue-orbital/avionics#104]
The intended PCB for avionics will use embedded systems rather than breakout boards to interface with sensors.

Design (or take from the datasheet) a circuit diagram of the MPU9250 Inertial Measurement Unit in kicad to be applied to the PCB at a later time.

Make an accurate parts list of components that will be required for this subassembly.

**Comment by ZecongLiang** [comment]
Here is a link to the MPU9250 on Sparkfun's website, which includes the Eagle files: https://www.sparkfun.com/products/13762
