### ISSUE TITLE
Generate a DS3231 Circuit Diagram in EAGLE

### ISSUE THREAD

**Issue by mchartigan** [purdue-orbital/avionics#105]
The avionics PCB will use embedded systems rather than a breakout board to interface with sensors.

A circuit diagram needs to be created in KiCad for the DS3231 Real-Time Clock. Use all available resources to complete this -- this clock is fairly common, so I would expect it to have pre-made circuit diagrams already.

Please keep an accurate parts list of components required for this subassembly.

**Comment by mchartigan** [comment]
[Helpful link](https://datasheets.maximintegrated.com/en/ds/DS3231.pdf) to the product datasheet

**Comment by ZecongLiang** [comment]
Here is a link to the DS3231 on Adafruit's website, which includes the Eagle files: https://learn.adafruit.com/adafruit-ds3231-precision-rtc-breakout/downloads
