### ISSUE TITLE
Radio Integration

### ISSUE THREAD

**Issue by mchartigan** [purdue-orbital/avionics#23]
Ground Station's radio needs to have fully functional autonomous communication with our flight computer.

**Comment by mchartigan** [comment]
Additionally: long range communication needs to be tested.

**Comment by kcsodetz** [comment]
Completed PR to integrate code (#72). Testing needed.

**Comment by kcsodetz** [comment]
Hapsis Alpha test completed. 0.75 mile range with current antenna setup. Launch and abort tests completed. Stability commands have yet to be tested.
