### ISSUE TITLE
3D Printed Parts at Cold Temps

### ISSUE THREAD

**Issue by colinam1** [purdue-orbital/avionics#31]

**Comment by sconkle** [comment]
![3D_Printed_Plastics_at_Cold_Temp](https://user-images.githubusercontent.com/47341072/67902480-acac5f80-fb3f-11e9-8b0b-c99c9a37a84d.jpg)

Here is an infographic from this video https://www.youtube.com/watch?v=w0JVXvSSEWs demonstrating that mosts types of plastic have a higher load strength at sub zero temperatures

**Comment by mchartigan** [comment]
Validated.
