### ISSUE TITLE
Design Ignition PCB

### ISSUE THREAD

**Issue by colinam1** [purdue-orbital/avionics#41]
Use Eagle

**Comment by colinam1** [comment]
https://easyeda.com/ This is a company that we can use for pcb manufacturing.

**Comment by ZecongLiang** [comment]
Finished. However, the switch footprint is TBD.

**Comment by mchartigan** [comment]
PCB replaced with 3V relay for HAPSIS Alpha

**Comment by mchartigan** [comment]
Now applicable to PCBv1
