### ISSUE TITLE
Work with Flight Systems to design QDM interface

### ISSUE THREAD

**Issue by colinam1** [purdue-orbital/avionics#43]
Requirements:
-Must not break critical electronics when payload detaches from balloon
-Must not tangle/break while payload spins under balloon
-Must have stable connection when necessary

Ideas:
-Look up charger for fossil smart watch gen5 - can spin without loosing connection

**Comment by sconkle** [comment]
Flight Systems has reached out to us for testing of the QDM system, awaiting updates for a test.

**Comment by mchartigan** [comment]
QDM system validated by HAPSIS Alpha -- 02/16/2020
