### ISSUE TITLE
Clarify logic of QDM circuit

### ISSUE THREAD

**Issue by sconkle** [purdue-orbital/avionics#46]
The QDM circuit is reading a 5V circuit through the gate, even with the QDM safety switch in the off position. The cause for this floating gate (whether it is the battery plugged in before the MCU or the MCU plugged in before the battery) needs to be determined.

**Comment by sconkle** [comment]
https://www.mouser.com/blog/dont-leave-your-pins-floating useful link with a possible solution: possibly moving/adding another pull up resistor

**Comment by colinam1** [comment]
I think this is done and primarily an issue in testing with a common ground. The QDM needs separate grounds for battery power and MCU power. Will mark as done according to @sconkle

**Comment by sconkle** [comment]
gg no re ez
