### ISSUE TITLE
Create power distribution diagram

### ISSUE THREAD

**Issue by colinam1** [purdue-orbital/avionics#56]

**Comment by ZecongLiang** [comment]
[Simplified Battery Power Diagram.pdf]
(https://github.com/purdue-orbital/avionics/files/3709776/Simplified.Battery.Power.Diagram.pdf)

**Comment by ZecongLiang** [comment]
[Simplified Battery Power Diagram.pdf](https://github.com/purdue-orbital/avionics/files/3753357/Simplified.Battery.Power.Diagram.pdf)
