### ISSUE TITLE
Rocket Battery Analysis

### ISSUE THREAD

**Issue by colinam1** [purdue-orbital/avionics#68]
Since pass through charging might be an issue, let's see if a standard anker battery of between 5,000 and 8,000 mAh would be enough to power the rocket flight computer and all peripherals for the time of flight (5-6 hours).

**Comment by sconkle** [comment]
Mark Tested, 16.07 Hours of Datalogging is capable using Anker Battery, Which meets our requirements for the duration of the flight.
