### ISSUE TITLE
Error checking

### ISSUE THREAD

**Issue by mchartigan** [purdue-orbital/avionics#69]
- sensor disconnects (QDM if gyroscope)
- Bad data from sensors: let ground station determine
- wrap reads in try/except and print error to log file (only once)
- if clock disconnects, switch to built-in clock
- lose connection with radio or radio physically disconnects: QDM
- if thread crashes, QDM
- lose connection with rocket: alert ground station

**Comment by kcsodetz** [comment]
Checking the connection with the radio can be accomplished by catching any errors with initialization or sending. I can look into that part.
